-- This migration intentionally left empty.
-- Admin password must be reset via the /auth/reset-admin endpoint using ORBIT_ADMIN_RESET_KEY,
-- or by running the bootstrap flow. Never commit password hashes to version control.
